// Service worker de la Salle des machines : garde les pages et les ressources pour jouer hors ligne.
// Pense à changer VERSION à chaque ajout de machine pour que les téléphones récupèrent la nouvelle liste.
const VERSION = 'promenade-1790643802';
const FICHIERS = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "app/icones/icone-192.png",
  "app/icones/icone-512.png",
  "jeux/masquerade-3d.html",
  "jeux/masquerade.html",
  "app/vignettes/masquerade-3d.jpg",
  "jeux/planches/masquerade-3d/s5-idle.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s5-win.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s6-idle.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s6-win.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s7-idle.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s7-win.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s8-idle.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s8-win.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s9-idle.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s9-win.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s10-idle.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/s10-win.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/scat-idle.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/scat-win.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/v-wild-wild-idle.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/v-wild-wild-win.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/v-wild-red-idle.webp?v=0392a81c",
  "jeux/planches/masquerade-3d/v-wild-red-win.webp?v=0392a81c",
  "jeux/dead-city-3d.html",
  "jeux/dead-city.html",
  "app/vignettes/dead-city-3d.jpg",
  "jeux/planches/dead-city-3d/s0-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s0-win.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s1-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s1-win.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s2-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s2-win.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s3-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s3-win.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s4-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s4-win.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s5-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s5-win.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s6-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s6-win.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s7-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/s7-win.webp?v=959c3259",
  "jeux/planches/dead-city-3d/scat-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/scat-win.webp?v=959c3259",
  "jeux/planches/dead-city-3d/v-wild-wild-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/v-wild-wild-win.webp?v=959c3259",
  "jeux/planches/dead-city-3d/v-wild-zero-idle.webp?v=959c3259",
  "jeux/planches/dead-city-3d/v-wild-zero-win.webp?v=959c3259",
  "jeux/champi-pop-3d.html",
  "jeux/champi-pop.html",
  "app/vignettes/champi-pop-3d.jpg",
  "jeux/planches/champi-pop-3d/s0-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s0-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s1-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s1-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s2-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s2-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s3-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s3-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s4-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s4-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s5-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s5-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s6-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s6-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s7-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/s7-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/scat-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/scat-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/v-power-grow-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/v-power-grow-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/v-power-color-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/v-power-color-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/v-power-heal-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/v-power-heal-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/v-power-stack-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/v-power-stack-win.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/v-power-ring-idle.webp?v=ea903f42",
  "jeux/planches/champi-pop-3d/v-power-ring-win.webp?v=ea903f42",
  "jeux/constella-3d.html",
  "jeux/constella.html",
  "app/vignettes/constella-3d.jpg",
  "jeux/planches/constella-3d/s0-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s0-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s1-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s1-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s2-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s2-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s3-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s3-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s4-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s4-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s5-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s5-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s6-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s6-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s7-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/s7-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/scat-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/scat-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/v-star-star-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/v-star-star-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/v-star-lit-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/v-star-lit-win.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/v-star-gold-idle.webp?v=9eb1fba6",
  "jeux/planches/constella-3d/v-star-gold-win.webp?v=9eb1fba6",
];
self.addEventListener('install', e => e.waitUntil(caches.open(VERSION).then(c => c.addAll(FICHIERS)).then(() => self.skipWaiting())));
self.addEventListener('activate', e => e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== VERSION).map(k => caches.delete(k)))).then(() => self.clients.claim())));
// réseau d'abord pour les pages (nouvelles versions), cache d'abord pour le reste du site (images, icônes)
self.addEventListener('fetch', e => {
  const req = e.request; if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== location.origin) return; // Three.js, polices : le navigateur s'en charge (un module mis en cache « opaque » casserait la 3D)
  const page = req.mode === 'navigate' || req.destination === 'iframe' || req.url.endsWith('.html');
  e.respondWith(page
    ? fetch(req).then(r => { const copy = r.clone(); caches.open(VERSION).then(c => c.put(req, copy)); return r; }).catch(() => caches.match(req, { ignoreSearch: true }))
    : caches.match(req).then(hit => hit || fetch(req).then(r => { if (r.ok || r.type === 'opaque') { const copy = r.clone(); caches.open(VERSION).then(c => c.put(req, copy)); } return r; })));
});
